language: php
dist: trusty
sudo: required

php:
- 5.6
- 7

env:
  global:
    - CLOUD_NAME=redcomponent
    - API_KEY=365447364384436
    - API_SECRET=Q94UM5kjZkZIrau8MIL93m0dN6U
    - GITHUB_TOKEN=4d92f9e8be0eddc0e54445ff45bf1ca5a846b609
    - ORGANIZATION=redCOMPONENT-COM
    - REPO=redEVENT

addons:
  firefox: "47.0.2"

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install

before_script:
  - "export DISPLAY=:99.0"
  - ./build/setup.sh
  - cd tests

script:
- echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
- vendor/bin/robo check:for-missed-debug-code
- vendor/bin/robo check:for-parse-errors
- vendor/bin/robo check:codestyle
- mv acceptance.suite.dist.yml acceptance.suite.yml
- vendor/bin/robo run:tests
- vendor/bin/robo send:screenshot-from-travis-to-github $CLOUD_NAME $API_KEY $API_SECRET $GITHUB_TOKEN $ORGANIZATION $REPO $TRAVIS_PULL_REQUEST;
- vendor/bin/robo run:unit-tests

notifications:
  slack: redweb:egb7X6jqHYp9PCwbUuQt0pVE
