<?php
/**
 * JLoaderTest
 *
 * @package   Joomla.UnitTest
 * @copyright Copyright (C) 2005 - 2012 Open Source Matters. All rights reserved.
 * @license   GNU General Public License
 */
//require_once 'PHPUnit/Framework.php';
require_once 'PHPUnit/Autoload.php';

require_once (BASEPATH.DS.'component'.DS.'site'.DS.'helpers'.DS.'recurrence.php');

/**
 * Test class for currency.
 * Generated by PHPUnit on 2009-10-16 at 23:32:06.
 *
 * @package	redFORM.UnitTest
 */
class maerskpluginTest extends JoomlaTestCase
{
	protected $plugin;

	/**
	 * Setup tests
	 *
	 * @return void
	 */
	protected function setUp()
	{
		parent::setUp();
		$this->plugin = $this->getPlugin();
	}

	/**
	 * test load plugin
	 *
	 * @return void
	 */
	public function testLoadplugin()
	{
		$this->assertInstanceOf('JPlugin', $this->plugin);
	}

	/**
	 * Test unsupported schema
	 *
	 * @return void
	 *
	 * @throws Exception
	 */
	public function testUnsupportedSchema()
	{
		try
		{
			$this->plugin->onHandle('maersk', '<RERERE></RERERE>');
		}
		catch (Exception $e)
		{
			if (!strstr($e->getMessage(), 'Parsing error: Unsupported schema'))
			{
				throw new Exception('bad exception:' . $e->getMessage());
			}
		}
	}

	/**
	 * Content provider
	 *
	 * @return array
	 */
	public function getTestSupportedInputSchemaData()
	{
		return array(
			array('<AttendeesRQ />'),
			array('<AttendeesRS />'),
			array('<CustomersCRMRQ />'),
			array('<CustomersRQ />'),
			array('<CustomersRS />'),
			array('<GetSessionAttendeesRS />'),
			array('<GetSessionsRS />'),
			array('<SessionsRQ />'),
			array('<SessionsRS />'),
		);
	}

	/**
	 * Test supported schema. Just test the top element
	 *
	 * @param   string  $schema  xml data
	 *
	 * @return void
	 *
	 * @throws Exception
	 *
	 * @dataProvider getTestSupportedInputSchemaData
	 */
	public function testSupportedInputSchema($schema)
	{
		try
		{
			$this->plugin->onHandle('maersk', $schema);
		}
		catch (Exception $e)
		{
			if (!strstr($e->getMessage(), 'Parsing error: Invalid xml data'))
			{
				throw new Exception('bad exception:' . $e->getMessage());
			}
		}
	}

	/**
	 * Content provider
	 *
	 * @return array
	 */
	public function getTestNotXmlDataData()
	{
		return array(
			array(null),
			array(''),
			array('adasdasd'),
			array(23)
		);
	}

	/**
	 * Test unsupported data
	 *
	 * @param   mixed  $data  data
	 *
	 * @return void
	 *
	 * @throws Exception
	 *
	 * @dataProvider getTestNotXmlDataData
	 */
	public function testNotXmlData($data)
	{
		try
		{
			$this->plugin->onHandle('maersk', $data);
		}
		catch (Exception $e)
		{
			if (!strstr($e->getMessage(), 'Parsing error') && !strstr($e->getMessage(), 'DOMDocument::loadXML()'))
			{
				throw new Exception('bad exception:' . $e->getMessage());
			}

			return;
		}

		$this->fail('An expected exception has not been raised.');
	}

	public function testCustomersCRMRQCreate()
	{
		$xml = file_get_contents(__DIR__ . '/xml/CustomersCRMRQ_1.xml');

		try
		{
			$this->plugin->onHandle('maersk', $xml);
		}
		catch(JDatabaseException $e)
		{
			// We should implement a database stub...
		}
	}

	/**
	 * Return plugin
	 *
	 * @param   array  $params  parameters
	 *
	 * @return plgRedeventsyncclientMaersk
	 */
	private function getPlugin($params = null)
	{
		require_once JPATH_SITE . '/plugins/redeventsyncclient/maersk/maersk.php';
		jimport('joomla.event.dispatcher');

		$dispatcher = JDispatcher::getInstance();
		$plugin = new plgRedeventsyncclientMaersk($dispatcher, $params);

		$logger = $this->getMock('ResyncHelperMessagelog', array('log'));
		$plugin->setDbLogger($logger);

		$client = $this->getMock('RedeventsyncClientMaersk', array('send'), array('http://mock.redweb.dk'));
		$plugin->setClient($client);

		return $plugin;
	}
}
