<?php
/**
 * JLoaderTest
 *
 * @package   Joomla.UnitTest
 * @copyright Copyright (C) 2005 - 2012 Open Source Matters. All rights reserved.
 * @license   GNU General Public License
 */
//require_once 'PHPUnit/Framework.php';
require_once 'PHPUnit/Autoload.php';

require_once (BASEPATH.DS.'component'.DS.'site'.DS.'helpers'.DS.'recurrence.php');

/**
 * Test class for currency.
 * Generated by PHPUnit on 2009-10-16 at 23:32:06.
 *
 * @package	redFORM.UnitTest
 */
class maerskpluginTest extends JoomlaTestCase
{
	/**
	 * test load plugin
	 *
	 * @return void
	 */
	public function testLoadplugin()
	{
		$plugin = $this->getPlugin();
		$this->assertInstanceOf('JPlugin', $plugin);
	}

	/**
	 * Test unsupported schema
	 *
	 * @return void
	 *
	 * @throws Exception
	 */
	public function testUnsupportedSchema()
	{
		$plugin = $this->getPlugin();

		try
		{
			$plugin->onHandle('maersk', '<RERERE></RERERE>');
		}
		catch (Exception $e)
		{
			if (!strstr($e->getMessage(), 'Parsing error: Unsupported schema'))
			{
				throw new Exception('bad exception:' . $e->getMessage());
			}
		}
	}

	/**
	 * Test supported schema
	 *
	 * @return void
	 *
	 * @throws Exception
	 */
	public function testSupportedSchema()
	{
		$plugin = $this->getPlugin();

		try
		{
			$plugin->onHandle('maersk', '<AttendeesRQ></AttendeesRQ>');
		}
		catch (Exception $e)
		{
			if (!strstr($e->getMessage(), 'Parsing error: Invalid xml data'))
			{
				throw new Exception('bad exception:' . $e->getMessage());
			}
		}
	}

	/**
	 * Content provider
	 *
	 * @return array
	 */
	public function getTestNotXmlDataData()
	{
		return array(
			array(null),
			array(''),
			array('adasdasd'),
			array(23)
		);
	}

	/**
	 * Test unsupported data
	 *
	 * @param   mixed  $data  data
	 *
	 * @return void
	 *
	 * @throws Exception
	 *
	 * @dataProvider getTestNotXmlDataData
	 */
	public function testNotXmlData($data)
	{
		$plugin = $this->getPlugin();

		try
		{
			$plugin->onHandle('maersk', $data);
		}
		catch (Exception $e)
		{
			if (!strstr($e->getMessage(), 'Parsing error') && !strstr($e->getMessage(), 'DOMDocument::loadXML()'))
			{
				throw new Exception('bad exception:' . $e->getMessage());
			}
		}

		$this->fail('An expected exception has not been raised.');
	}

	/**
	 * Return plugin
	 *
	 * @param   array  $params  parameters
	 *
	 * @return plgRedeventsyncclientMaersk
	 */
	private function getPlugin($params = null)
	{
		require_once JPATH_SITE . '/plugins/redeventsyncclient/maersk/maersk.php';
		jimport('joomla.event.dispatcher');

		$dispatcher = JDispatcher::getInstance();
		$params = array();
		$plugin = new plgRedeventsyncclientMaersk($dispatcher, $params);

		$logger = $this->getMock('ResyncHelperMessagelog');
		$logger->expects($this->any())
			->method('log');

		$plugin->setDbLogger($logger);

		return $plugin;
	}
}
