CREATE TABLE IF NOT EXISTS `#__redevent_event_template` (
  `id` int(11) unsigned NOT NULL auto_increment,
  `name` VARCHAR(100) NOT NULL default '',
  `redform_id` int(11) default NULL,
  `meta_keywords` varchar(200) NOT NULL default '',
  `meta_description` varchar(255) NOT NULL default '',
  `mailflow_id` int(11) NOT NULL default '0',
  `juser` tinyint(1) NOT NULL default '1' COMMENT 'Create user on registration',
  `details_layout` tinyint(2) NOT NULL,
  `notify` tinyint(1) NOT NULL default '0',
  `notify_subject` varchar(255) NOT NULL default '',
  `notify_body` text NOT NULL,
  `notify_on_list_body` text NOT NULL,
  `notify_off_list_body` text NOT NULL,
  `notify_on_list_subject` varchar(255) NOT NULL,
  `notify_off_list_subject` varchar(255) NOT NULL,
  `show_names` tinyint(1) NOT NULL default '1',
  `activate` tinyint(1) NOT NULL default '0',
  `notify_confirm_subject` varchar(255) NOT NULL default '',
  `notify_confirm_body` text NOT NULL,
  `showfields` text,
  `confirmation_message` text,
  `submission_types` varchar(255) default 'email',
  `submission_type_email` text,
  `submission_type_external` varchar(255) NOT NULL,
  `submission_type_phone` text,
  `submission_type_formal_offer` text,
  `submission_type_formal_offer_subject` varchar(255) default NULL,
  `submission_type_formal_offer_body` text,
  `submission_type_formal_offer_pdf` text,
  `show_submission_type_webform_formal_offer` tinyint(1) NOT NULL default '0',
  `submission_type_webform` text,
  `submission_type_email_subject` varchar(255) default NULL,
  `submission_type_email_body` text,
  `submission_type_email_pdf` text,
  `review_message` text,
  `send_pdf_form` tinyint(1) NOT NULL default '0',
  `pdf_form_data` tinyint(1) NOT NULL default '0',
  `submission_type_webform_formal_offer` text,
  `paymentaccepted` text NOT NULL,
  `paymentprocessing` text NOT NULL,
  `enable_ical` tinyint(2) NOT NULL default '0',
  `enable_activation_confirmation` TINYINT( 1 ) NOT NULL DEFAULT  '0',
  `language` char(7) NOT NULL,
  `checked_out` int(11) NOT NULL default '0',
  `checked_out_time` datetime NOT NULL default '0000-00-00 00:00:00',
  PRIMARY KEY  (`id`),
  KEY (`redform_id`),
  KEY (`mailflow_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `#__redevent_event_template` (
  `id`,
  `name`,
  `redform_id`,
  `meta_keywords`,
  `meta_description`,
  `mailflow_id`,
  `juser`,
  `details_layout`,
  `notify`,
  `notify_subject`,
  `notify_body`,
  `notify_on_list_body`,
  `notify_off_list_body`,
  `notify_on_list_subject`,
  `notify_off_list_subject`,
  `show_names`,
  `activate`,
  `notify_confirm_subject`,
  `notify_confirm_body`,
  `showfields`,
  `confirmation_message`,
  `submission_types`,
  `submission_type_email`,
  `submission_type_external`,
  `submission_type_phone`,
  `submission_type_formal_offer`,
  `submission_type_formal_offer_subject`,
  `submission_type_formal_offer_body`,
  `submission_type_formal_offer_pdf`,
  `show_submission_type_webform_formal_offer`,
  `submission_type_webform`,
  `submission_type_email_subject`,
  `submission_type_email_body`,
  `submission_type_email_pdf`,
  `review_message`,
  `send_pdf_form`,
  `pdf_form_data`,
  `submission_type_webform_formal_offer`,
  `paymentaccepted`,
  `paymentprocessing`,
  `enable_ical`,
  `enable_activation_confirmation`,
  `language`
)
SELECT
  `id`,
  CONCAT(`title`, ' - Template'),
  `redform_id`,
  `meta_keywords`,
  `meta_description`,
  `mailflow_id`,
  `juser`,
  `details_layout`,
  `notify`,
  `notify_subject`,
  `notify_body`,
  `notify_on_list_body`,
  `notify_off_list_body`,
  `notify_on_list_subject`,
  `notify_off_list_subject`,
  `show_names`,
  `activate`,
  `notify_confirm_subject`,
  `notify_confirm_body`,
  `showfields`,
  `confirmation_message`,
  `submission_types`,
  `submission_type_email`,
  `submission_type_external`,
  `submission_type_phone`,
  `submission_type_formal_offer`,
  `submission_type_formal_offer_subject`,
  `submission_type_formal_offer_body`,
  `submission_type_formal_offer_pdf`,
  `show_submission_type_webform_formal_offer`,
  `submission_type_webform`,
  `submission_type_email_subject`,
  `submission_type_email_body`,
  `submission_type_email_pdf`,
  `review_message`,
  `send_pdf_form`,
  `pdf_form_data`,
  `submission_type_webform_formal_offer`,
  `paymentaccepted`,
  `paymentprocessing`,
  `enable_ical`,
  `enable_activation_confirmation`,
  `language`
FROM `#__redevent_events`;

ALTER TABLE `#__redevent_events` ADD COLUMN `template_id` int(11) NOT NULL;
UPDATE `#__redevent_events` SET `template_id` = `id`;
