CREATE TABLE IF NOT EXISTS `#__redevent_events` (
  `id` int(11) unsigned NOT NULL auto_increment,
  `title` varchar(100) NOT NULL default '',
  `alias` varchar(100) NOT NULL default '',
  `created_by` int(11) unsigned NOT NULL default '0',
  `modified` datetime NOT NULL,
  `modified_by` int(11) unsigned NOT NULL default '0',
  `author_ip` varchar(15) NOT NULL default '',
  `created` datetime NOT NULL,
  `datdescription` mediumtext NOT NULL,
  `meta_keywords` varchar(200) NOT NULL default '',
  `meta_description` varchar(255) NOT NULL default '',
  `recurrence_number` int(2) NOT NULL default '0',
  `recurrence_type` int(2) NOT NULL default '0',
  `recurrence_counter` date NOT NULL default '0000-00-00',
  `datimage` varchar(100) NOT NULL default '',
  `checked_out` int(11) NOT NULL default '0',
  `checked_out_time` datetime NOT NULL default '0000-00-00 00:00:00',
  `registra` tinyint(1) NOT NULL default '0',
  `unregistra` tinyint(1) NOT NULL default '0',
  `published` tinyint(1) NOT NULL default '0',
  `notify` tinyint(1) NOT NULL default '0',
  `notify_subject` varchar(45) NOT NULL default '',
  `notify_body` text NOT NULL,
  `redform` tinyint(1) NOT NULL default '0',
  `redform_id` int(11) default NULL,
  `registeruser` tinyint(1) NOT NULL default '1',
  `juser` tinyint(1) NOT NULL default '1',
  `notify_on_list_body` text NOT NULL,
  `notify_off_list_body` text NOT NULL,
  `notify_on_list_subject` varchar(45) NOT NULL,
  `notify_off_list_subject` varchar(45) NOT NULL,
  `show_names` tinyint(1) NOT NULL default '1',
  `activate` tinyint(1) NOT NULL default '0',
  `notify_confirm_subject` varchar(45) NOT NULL default '',
  `notify_confirm_body` text NOT NULL,
  `showfields` text,
  `show_waitinglist` tinyint(1) NOT NULL default '1',
  `show_attendants` tinyint(1) NOT NULL default '1',
  `confirmation_message` text,
  `submission_types` varchar(255) default 'email',
  `course_code` varchar(255) NOT NULL,
  `submission_type_email` text,
  `submission_type_external` varchar(255) NOT NULL,
  `submission_type_phone` text,
  `max_multi_signup` int(2) unsigned NOT NULL default '1',
  `submission_type_formal_offer` text,
  `submission_type_formal_offer_subject` varchar(75) default NULL,
  `submission_type_webform` text,
  `submission_type_formal_offer_body` text,
  `submission_type_email_body` text,
  `submission_type_formal_offer_pdf` text,
  `submission_type_email_pdf` text,
  `submission_type_email_subject` varchar(75) default NULL,
  `review_message` text,
  `send_pdf_form` tinyint(1) NOT NULL default '0',
  `pdf_form_data` tinyint(1) NOT NULL default '0',
  `submission_type_webform_formal_offer` text,
  PRIMARY KEY  (`id`)
) TYPE=MyISAM CHARACTER SET `utf8` COLLATE `utf8_general_ci`;

CREATE TABLE IF NOT EXISTS `#__redevent_venues` (
`id` int(11) unsigned NOT NULL auto_increment,
`venue` varchar(50) NOT NULL default '',
`alias` varchar(100) NOT NULL default '',
`url` varchar(200)  NOT NULL default '',
`street` varchar(50) default NULL,
`plz` varchar(20) default NULL,
`city` varchar(50) default NULL,
`state` varchar(50) default NULL,
`country` varchar(2) default NULL,
`locdescription` mediumtext NOT NULL,
`meta_keywords` text NOT NULL,
`meta_description` text NOT NULL,
`locimage` varchar(100) NOT NULL default '',
`map` tinyint(4) NOT NULL default '0',
`created_by` int(11) unsigned NOT NULL default '0',
`author_ip` varchar(15) NOT NULL default '',
`created` datetime NOT NULL,
`modified` datetime NOT NULL,
`modified_by` int(11) unsigned NOT NULL default '0',
`published` tinyint(1) NOT NULL default '0',
`checked_out` int(11) NOT NULL default '0',
`checked_out_time` datetime NOT NULL default '0000-00-00 00:00:00',
`ordering` int(11) NOT NULL default '0',
PRIMARY KEY  (`id`)
) TYPE=MyISAM CHARACTER SET `utf8` COLLATE `utf8_general_ci`;

CREATE TABLE IF NOT EXISTS `#__redevent_categories` (
`id` int(11) unsigned NOT NULL auto_increment,
`parent_id` int(11) unsigned NOT NULL default '0',
`catname` varchar(100) NOT NULL default '',
`alias` varchar(100) NOT NULL default '',
`catdescription` mediumtext NOT NULL,
`meta_keywords` text NOT NULL,
`meta_description` text NOT NULL,
`image` varchar(100) NOT NULL default '',
`published` tinyint(1) NOT NULL default '0',
`checked_out` int(11) NOT NULL default '0',
`checked_out_time` datetime NOT NULL default '0000-00-00 00:00:00',
`access` int(11) unsigned NOT NULL default '0',
`groupid` int(11) NOT NULL default '0',
`ordering` int(11) NOT NULL default '0',
`lft` int(11) NOT NULL default '0',
`rgt` int(11) NOT NULL default '0',
PRIMARY KEY  (`id`)
) TYPE=MyISAM CHARACTER SET `utf8` COLLATE `utf8_general_ci`;

CREATE TABLE IF NOT EXISTS `#__redevent_register` (
`id` int(11) unsigned NOT NULL auto_increment,
`xref` int(11) NOT NULL default '0',
`uid` int(11) NOT NULL default '0',
`uregdate` varchar(50) NOT NULL default '',
`uip` varchar(15) NOT NULL default '',
`submit_key` varchar(45) NOT NULL,
PRIMARY KEY  (`id`)
) TYPE=MyISAM CHARACTER SET `utf8` COLLATE `utf8_general_ci`;

CREATE TABLE IF NOT EXISTS `#__redevent_groups` (
`id` int(11) unsigned NOT NULL auto_increment,
`name` varchar(150) NOT NULL default '',
`description` mediumtext NOT NULL,
`checked_out` int(11) NOT NULL default '0',
`checked_out_time` datetime NOT NULL default '0000-00-00 00:00:00',
PRIMARY KEY  (`id`)
) TYPE=MyISAM CHARACTER SET `utf8` COLLATE `utf8_general_ci`;

CREATE TABLE IF NOT EXISTS `#__redevent_groupmembers` (
`group_id` INT( 11 ) NOT NULL DEFAULT '0',
`member` INT( 11 ) NOT NULL DEFAULT '0'
) TYPE = MYISAM CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS `#__redevent_settings` (
  `id` int(11) NOT NULL,
  `oldevent` tinyint(4) NOT NULL,
  `minus` tinyint(4) NOT NULL,
  `showtime` tinyint(4) NOT NULL,
  `showtitle` tinyint(4) NOT NULL,
  `showlocate` tinyint(4) NOT NULL,
  `showcity` tinyint(4) NOT NULL,
  `showmapserv` tinyint(4) NOT NULL,
  `map24id` varchar(20) NOT NULL,
  `gmapkey` varchar(255) NOT NULL,
  `tablewidth` varchar(20) NOT NULL,
  `datewidth` varchar(20) NOT NULL,
  `titlewidth` varchar(20) NOT NULL,
  `locationwidth` varchar(20) NOT NULL,
  `citywidth` varchar(20) NOT NULL,
  `datename` varchar(100) NOT NULL,
  `titlename` varchar(100) NOT NULL,
  `locationname` varchar(100) NOT NULL,
  `cityname` varchar(100) NOT NULL,
  `formatdate` varchar(100) NOT NULL,
  `formattime` varchar(100) NOT NULL,
  `timename` varchar(50) NOT NULL,
  `showdetails` tinyint(4) NOT NULL,
  `showtimedetails` tinyint(4) NOT NULL,
  `showevdescription` tinyint(4) NOT NULL,
  `showdetailstitle` tinyint(4) NOT NULL,
  `showdetailsadress` tinyint(4) NOT NULL,
  `showlocdescription` tinyint(4) NOT NULL,
  `showlinkvenue` tinyint(4) NOT NULL,
  `showdetlinkvenue` tinyint(4) NOT NULL,
  `delivereventsyes` tinyint(4) NOT NULL,
  `mailinform` tinyint(4) NOT NULL,
  `mailinformrec` varchar(150) NOT NULL,
  `mailinformuser` tinyint(4) NOT NULL,
  `datdesclimit` varchar(15) NOT NULL,
  `autopubl` tinyint(4) NOT NULL,
  `deliverlocsyes` tinyint(4) NOT NULL,
  `autopublocate` tinyint(4) NOT NULL,
  `showcat` tinyint(4) NOT NULL,
  `catfrowidth` varchar(20) NOT NULL,
  `catfroname` varchar(100) NOT NULL,
  `evdelrec` tinyint(4) NOT NULL,
  `evpubrec` tinyint(4) NOT NULL,
  `locdelrec` tinyint(4) NOT NULL,
  `locpubrec` tinyint(4) NOT NULL,
  `sizelimit` varchar(20) NOT NULL,
  `imagehight` varchar(20) NOT NULL,
  `imagewidth` varchar(20) NOT NULL,
  `gddisabled` tinyint(4) NOT NULL,
  `imageenabled` tinyint(4) NOT NULL,
  `comunsolution` tinyint(4) NOT NULL,
  `comunoption` tinyint(4) NOT NULL,
  `catlinklist` tinyint(4) NOT NULL,
  `showfroregistra` tinyint(4) NOT NULL,
  `showfrounregistra` tinyint(4) NOT NULL,
  `eventedit` tinyint(4) NOT NULL,
  `eventeditrec` tinyint(4) NOT NULL,
  `eventowner` tinyint(4) NOT NULL,
  `venueedit` tinyint(4) NOT NULL,
  `venueeditrec` tinyint(4) NOT NULL,
  `venueowner` tinyint(4) NOT NULL,
  `lightbox` tinyint(4) NOT NULL,
  `meta_keywords` varchar(255) NOT NULL,
  `meta_description` varchar(255) NOT NULL,
  `showstate` tinyint(4) NOT NULL,
  `statename` varchar(100) NOT NULL,
  `statewidth` varchar(20) NOT NULL,
  `regname` tinyint(4) NOT NULL,
  `storeip` tinyint(4) NOT NULL,
  `commentsystem` tinyint(4) NOT NULL,
  `lastupdate` varchar(20) NOT NULL default '',
  `checked_out` int(11) NOT NULL default '0',
  `checked_out_time` datetime NOT NULL default '0000-00-00 00:00:00',
  `defaultredformid` int(11) NOT NULL default '1',
  `currency_decimals` varchar(10) default 'decimals',
  `currency_decimal_separator` varchar(1) default ',',
  `currency_thousand_separator` varchar(1) default '.',
  `signup_external_text` VARCHAR( 50 ) NOT NULL DEFAULT 'SIGNUP_EXTERNAL',
  `signup_external_img` VARCHAR( 50 ) NOT NULL DEFAULT 'external_icon.gif',
  `signup_webform_text` VARCHAR( 50 ) NOT NULL DEFAULT 'SIGNUP_WEBFORM',
  `signup_webform_img` VARCHAR( 50 ) NOT NULL DEFAULT 'form_icon.gif',
  `signup_email_text` VARCHAR( 50 ) NOT NULL DEFAULT 'SIGNUP_EMAIL',
  `signup_email_img` VARCHAR( 50 ) NOT NULL DEFAULT 'email_icon.gif',
  `signup_formal_offer_text` VARCHAR( 50 ) NOT NULL DEFAULT 'SIGNUP_FORMAL_OFFER',
  `signup_formal_offer_img` VARCHAR( 50 ) NOT NULL DEFAULT 'formal_icon.gif',
  `signup_phone_text` VARCHAR( 50 ) NOT NULL DEFAULT 'SIGNUP_PHONE',
  `signup_phone_img` VARCHAR( 50 ) NOT NULL DEFAULT 'phone_icon.gif',
  UNIQUE KEY `id` (`id`)
) TYPE = MYISAM CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS `#__redevent_event_venue_xref` (
  `id` int(11) unsigned NOT NULL auto_increment,
  `eventid` int(11) unsigned NOT NULL,
  `venueid` int(11) unsigned NOT NULL,
  `dates` date NOT NULL default '0000-00-00',
  `enddates` date NULL default NULL,
  `times` time NULL default NULL,
  `endtimes` time NULL default NULL,
  `maxattendees` int(11) NOT NULL default '0',
  `maxwaitinglist` int(11) NOT NULL default '0',
  `course_credit` int(11) NOT NULL,
  `course_price` decimal(12,2) default '0.00',
  `published` tinyint(1) NOT NULL default '0',
  PRIMARY KEY  (`id`),
  UNIQUE KEY `eventvenue` (`eventid`,`venueid`,`dates`,`endtimes`,`times`,`enddates`)
) COMMENT='Event Venue Cross reference' CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS `#__redevent_event_category_xref` (
  `event_id` int(11) NOT NULL,
  `category_id` int(11) NOT NULL
) COMMENT='Event Category Cross reference' CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS `#__redevent_textlibrary` (
  `id` tinyint(4) NOT NULL auto_increment,
  `text_name` varchar(255) default NULL,
  `text_description` varchar(255) default NULL,
  `text_field` text,
  `checked_out` int(11) NOT NULL default '0',
  `checked_out_time` datetime default '0000-00-00 00:00:00',
  PRIMARY KEY  (`id`),
  UNIQUE KEY `id` (`id`),
  UNIQUE KEY `text_name` (`text_name`)
) TYPE = MYISAM CHARACTER SET utf8 COLLATE utf8_general_ci;


CREATE TABLE IF NOT EXISTS `#__redevent_venues_categories` (
  `id` int(11) unsigned NOT NULL auto_increment,
  `parent_id` int(11) unsigned NOT NULL default '0',
  `name` varchar(100) NOT NULL,
  `alias` varchar(100) NOT NULL default '',
  `description` mediumtext NOT NULL,
  `meta_keywords` text NOT NULL,
  `meta_description` text NOT NULL,
  `image` varchar(100) NOT NULL default '',
  `published` tinyint(1) NOT NULL default '0',
  `checked_out` int(11) NOT NULL default '0',
  `checked_out_time` datetime NOT NULL default '0000-00-00 00:00:00',
  `access` int(11) unsigned NOT NULL default '0',
  `groupid` int(11) NOT NULL default '0',
  `ordering` int(11) NOT NULL default '0',
  `lft` int(11) NOT NULL default '0',
  `rgt` int(11) NOT NULL default '0',
  PRIMARY KEY  (`id`)
) TYPE = MYISAM CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS `#__redevent_venue_category_xref` (
  `venue_id` int(11) NOT NULL,
  `category_id` int(11) NOT NULL
) TYPE = MYISAM CHARACTER SET utf8 COLLATE utf8_general_ci;